---
- name: Cria o diretorio de instalacao 
  file:
    path: "{{ ROOT_DATA_DIR }}"
    state: directory
    mode: '0755'

- name: Copia o arquivo docker-compose.yml para o host remoto
  template:
    src: docker-compose.yml.j2
    dest: "{{ ROOT_DATA_DIR }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Executa o Docker Compose para iniciar os containers
  command: docker compose up -d
  args:
    chdir: "{{ ROOT_DATA_DIR }}"
