---
- name: Verifica cluster
  command: |
    kubectl get nodes
  register: rke_output
  changed_when: false
  failed_when: rke_output.rc != 0
  when: not ansible_check_mode
  run_once: true

- name: Verificar nós
  command: |
    kubectl get nodes -o wide
  register: rke_output
  changed_when: false
  failed_when: rke_output.rc != 0
  when: not ansible_check_mode
  run_once: true

- name: Verificar pods do sistema
  command: |
    kubectl get pods -A
  register: rke_output
  changed_when: false
  failed_when: rke_output.rc != 0
  when: not ansible_check_mode
  run_once: true
