---
- name: Ensure decompression utilities are installed (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - tar
      - gzip
      - bzip2
      - xz-utils
      - unzip
      - zstd
    state: present
    update_cache: yes # Ensure package cache is updated
  become: true # Required to install packages
  when: "ansible_facts['distribution'] == 'Ubuntu' or ansible_facts['distribution'] == 'Debian'"

# ... (existing tasks for user creation, sudo, RKE deployment)
- name: Create user 'pgm_user'
  user:
    name: pgm_user
    groups: docker
    append: yes
    shell: /bin/bash
    state: present
  become: true

- name: Configure sudo without password for 'pgm-user'
  copy:
    dest: /etc/sudoers.d/pgm_user
    content: "pgm_user ALL=(ALL) NOPASSWD: ALL"
  become: true

- name: Garantir diretório .ssh
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'
  run_once: true

- name: Copiar chave SSH
  copy:
    src: "/home/pgmadmin/.ssh/id_rsa"  # CAMINHO LOCAL DA SUA CHAVE
    dest: "{{ ssh_key_path }}"
    mode: '0600'
  run_once: true
  when: not ansible_check_mode

- name: Ensure $HOME/.kube directory exists
  file:
    path: "{{ ansible_env.HOME }}/.kube" # Use ansible_env.HOME for robustness
    state: directory
    mode: '0755'
  run_once: true # Should run once, typically on the control node or where kubectl will be used
  # become: true # Usually user's home directory, but depends on Ansible connection user

- include_tasks: deploy-rke.yml
  # This should target the control plane node or run_once if rke is executed from ansible master
  # For simplicity, let's assume the play targets k8s-tools-controlplane for these tasks

- include_tasks: verificacao-rke.yml
  # Similar targeting as deploy-rke.yml

- name: Deploy Rancher
  include_tasks: deploy-rancher.yml
  # This should also target the k8s-tools-controlplane node(s)
  # The tasks inside deploy-rancher.yml use `when: inventory_hostname in groups['k8s-tools-controlplane'][0]`

- name: Import k8s-desenv Cluster into k8s-tools Rancher (Guidance)
  include_tasks: manage_desenv_cluster.yml
  # This should also target the k8s-tools-controlplane node(s)
  when: "inventory_hostname in groups['k8s-tools-controlplane'][0]" # Ensure it runs on the correct host
